### PR TITLE
Release fly-mocha v0.4.2

### PR DESCRIPTION
**Pull request by pine**
Hi @bucaran.

I want to use latest fly-mocha from the npm repository :smile:

Thank you.

### CODE REVIEW

**Comment by pine613** [comment]
If you are busy, whould you let me maintenance the module ?

**Comment by bucaran** [comment]
@pine613 I am sorry, I couldn't get back at your earlier today. I will do as you requested.

**Comment by pine613** [comment]
Thank you!!

**Comment by pine613** [comment]
I plan to release fly-mocha v0.4.2.

**Comment by bucaran** [comment]
Yes, sir!

**Pull request merged**
