### PR TITLE
Fly v1.x is Out!

### PR DESCRIPTION
**Pull request by pine613**
Fly v1.x is not had Babel :persevere:

### CODE REVIEW

**Comment by pine613** [comment]
Oh... Test failed, but Fly doesn't support Node 0.11.x now ?
https://github.com/bucaran/fly/blob/master/.travis.yml

**Comment by pine613** [comment]
@bucaran @lukeed Whould you review this PR ?

**Comment by bucaran** [comment]
LGTM

@lukeed I think we should be able to drop the --harmony flag soon along with support for Node 0.12.

Thoughts?

**Comment by lukeed** [comment]
@pine613 looks fine to me

@bucaran Can't drop harmony without all these plugins breaking... `const`, `let`, `for of`, arrows... all require it.

Also can't/shouldn't drop 0.12. It's still nearly (or at least) 25% of commercial usage. Node v3 through 5 is barely 20% combined.

**Comment by bucaran** [comment]
@lukeed Is anyone really using Fly in 0.12? Seems kind of incredible. BTW originally, the harmony flag was used only to support generators, the ES6 syntax came later.

**Comment by lukeed** [comment]
@bucaran Unfortunately I don't think we have a way of measuring that. But as a whole, NPM's active percentage of 0.12 is pretty shocking. 

Re: harmony. Right, but now with the 'downgrade' to ES5, we'd have to keep harmony around for all the plugins that _are_ using minor ES6 syntax bits.... at least until `fly-esnext` and `fly-plugins` are out. I havent had time to work on those lately.

**Comment by pine613** [comment]
Hi @bucaran @lukeed.

Whould you like to resolve `--harmony` flag problems in another new issues ?
I want you to use fly-mocha with Fly v1.x :pray:

Thank you.

**Comment by pine613** [comment]
:pray:

**Comment by pine613** [comment]
Hi @lukeed. How about this…? :pray:

**Comment by bucaran** [comment]
@lukeed I think what @pine613 is saying is that we should close the issue :laughing: 

@pine613 Is that correct?

**Comment by lukeed** [comment]
@pine613 @bucaran still looks good to me! Not sure why/if you guys were waiting on me? 

Sorry for any confusion.

**Comment by pine613** [comment]
Thank you!!!

**Pull request merged**
